export const BURSA_SECTORS = [
  "TECHNOLOGY",
  "PLANTATION",
  "FINANCIAL_SERVICES",
  "CONSUMER_PRODUCTS",
  "INDUSTRIAL_PRODUCTS",
  "REITS",
  "ENERGY",
  "HEALTHCARE",
  "CONSTRUCTION",
];

export const FIELD_LABELS: Record<string, string> = {
  // Income Statement
  revenue: "Revenue",
  nonOperatingRevenue: "Non-Operating Revenue",
  costOfGoodsSold: "Cost of Goods Sold (COGS)",
  grossProfit: "Gross Profit",
  operatingExpenses: "Operating Expenses (OPEX)",
  sgaExpenses: "SG&A Expenses",
  researchDevelopment: "R&D Expenses",
  depreciation: "Depreciation",
  amortization: "Amortization",
  ebit: "EBIT",
  ebitda: "EBITDA",
  operatingProfit: "Operating Profit",
  profitBeforeTax: "Profit Before Tax",
  taxExpense: "Tax Expense",
  effectiveTaxRate: "Effective Tax Rate",
  netProfit: "Net Profit / PAT",
  retainedEarnings: "Retained Earnings",
  financeIncome: "Finance Income",
  financeCost: "Finance Cost",

  // Balance Sheet
  totalAssets: "Total Assets",
  currentAssets: "Current Assets",
  nonCurrentAssets: "Non-Current Assets",
  cashAndEquivalents: "Cash & Equivalents",
  accountsReceivable: "Accounts Receivable",
  inventory: "Inventory",
  shortTermInvestments: "Short-Term Investments",
  ppe: "Property, Plant & Equipment",
  intangibleAssets: "Intangible Assets",
  goodwill: "Goodwill",
  totalLiabilities: "Total Liabilities",
  currentLiabilities: "Current Liabilities",
  accountsPayable: "Accounts Payable",
  shortTermDebt: "Short-Term Debt",
  nonCurrentLiabilities: "Non-Current Liabilities",
  longTermDebt: "Long-Term Debt",
  bondsPayable: "Bonds Payable",
  totalEquity: "Total Equity",
  commonStock: "Common Stock",
  preferredStock: "Preferred Stock",
  paidInCapital: "Paid-in Capital",

  // Cash Flow
  operatingCashFlow: "Operating Cash Flow",
  investingCashFlow: "Investing Cash Flow",
  financingCashFlow: "Financing Cash Flow",
  freeCashFlow: "Free Cash Flow",
  capitalExpenditure: "Capital Expenditure",

  // Ratios
  roe: "Return on Equity (ROE)",
  roa: "Return on Assets (ROA)",
  roic: "Return on Invested Capital",
  grossMargin: "Gross Margin",
  operatingMargin: "Operating Margin",
  netProfitMargin: "Net Profit Margin",
  currentRatio: "Current Ratio",
  quickRatio: "Quick Ratio",
  cashRatio: "Cash Ratio",
  debtToEquity: "Debt to Equity",
  debtRatio: "Debt Ratio",
  interestCoverage: "Interest Coverage",
  assetTurnover: "Asset Turnover",
  inventoryTurnover: "Inventory Turnover",
  receivablesTurnover: "Receivables Turnover",
  payablesTurnover: "Payables Turnover",
  eps: "Earnings Per Share (EPS)",
  dilutedEps: "Diluted EPS",
  peRatio: "P/E Ratio",
  totalDividendPaid: "Total Dividend Paid",
  dividendYield: "Dividend Yield",
  dividendPerShare: "Dividend Per Share",
  dividendPayoutRatio: "Payout Ratio",
  retentionRatio: "Retention Ratio",
  
  // Growth
  revenueGrowth: "Revenue Growth",
  netIncomeGrowth: "Net Income Growth",
  cagr: "CAGR",

  // Market Data
  sharePrice: "Share Price",
  marketCapitalization: "Market Capitalization",
  sharesOutstanding: "Shares Outstanding",
  weightedAverageSharesOutstanding: "Weighted Average Shares Outstanding",
  dilutedSharesOutstanding: "Diluted Shares Outstanding",

  // Advanced
  enterpriseValue: "Enterprise Value",
  evEbitda: "EV/EBITDA",
  fcfYield: "FCF Yield",
  eva: "Economic Value Added",
  workingCapital: "Working Capital",
  netWorkingCapital: "Net Working Capital",
};

export const CATEGORY_LABELS: Record<string, string> = {
  incomeStatement: "📊 Income Statement",
  balanceSheet: "🏦 Balance Sheet",
  cashFlow: "💵 Cash Flow",
  ratios: "📈 Ratios & Metrics",
  growth: "📉 Growth Metrics",
  marketData: "💰 Market Data",
  advanced: "🧠 Advanced Metrics",
};

export const FINANCIAL_DICTIONARY: Record<string, { category: string }> = {
  revenue: { category: "incomeStatement" },
  nonOperatingRevenue: { category: "incomeStatement" },
  costOfGoodsSold: { category: "incomeStatement" },
  grossProfit: { category: "incomeStatement" },
  operatingExpenses: { category: "incomeStatement" },
  sgaExpenses: { category: "incomeStatement" },
  researchDevelopment: { category: "incomeStatement" },
  depreciation: { category: "incomeStatement" },
  amortization: { category: "incomeStatement" },
  ebit: { category: "incomeStatement" },
  ebitda: { category: "incomeStatement" },
  operatingProfit: { category: "incomeStatement" },
  profitBeforeTax: { category: "incomeStatement" },
  taxExpense: { category: "incomeStatement" },
  effectiveTaxRate: { category: "incomeStatement" },
  netProfit: { category: "incomeStatement" },
  retainedEarnings: { category: "incomeStatement" },
  financeIncome: { category: "incomeStatement" },
  financeCost: { category: "incomeStatement" },

  totalAssets: { category: "balanceSheet" },
  currentAssets: { category: "balanceSheet" },
  nonCurrentAssets: { category: "balanceSheet" },
  cashAndEquivalents: { category: "balanceSheet" },
  accountsReceivable: { category: "balanceSheet" },
  inventory: { category: "balanceSheet" },
  shortTermInvestments: { category: "balanceSheet" },
  ppe: { category: "balanceSheet" },
  intangibleAssets: { category: "balanceSheet" },
  goodwill: { category: "balanceSheet" },
  totalLiabilities: { category: "balanceSheet" },
  currentLiabilities: { category: "balanceSheet" },
  accountsPayable: { category: "balanceSheet" },
  shortTermDebt: { category: "balanceSheet" },
  nonCurrentLiabilities: { category: "balanceSheet" },
  longTermDebt: { category: "balanceSheet" },
  bondsPayable: { category: "balanceSheet" },
  totalEquity: { category: "balanceSheet" },
  commonStock: { category: "balanceSheet" },
  preferredStock: { category: "balanceSheet" },
  paidInCapital: { category: "balanceSheet" },

  operatingCashFlow: { category: "cashFlow" },
  investingCashFlow: { category: "cashFlow" },
  financingCashFlow: { category: "cashFlow" },
  freeCashFlow: { category: "cashFlow" },
  capitalExpenditure: { category: "cashFlow" },

  roe: { category: "ratios" },
  roa: { category: "ratios" },
  roic: { category: "ratios" },
  grossMargin: { category: "ratios" },
  operatingMargin: { category: "ratios" },
  netProfitMargin: { category: "ratios" },
  currentRatio: { category: "ratios" },
  quickRatio: { category: "ratios" },
  cashRatio: { category: "ratios" },
  debtToEquity: { category: "ratios" },
  debtRatio: { category: "ratios" },
  interestCoverage: { category: "ratios" },
  assetTurnover: { category: "ratios" },
  inventoryTurnover: { category: "ratios" },
  receivablesTurnover: { category: "ratios" },
  payablesTurnover: { category: "ratios" },
  eps: { category: "ratios" },
  dilutedEps: { category: "ratios" },
  peRatio: { category: "ratios" },
  totalDividendPaid: {category: "ratios"},
  dividendYield: { category: "ratios" },
  dividendPerShare: { category: "ratios" },
  dividendPayoutRatio: { category: "ratios" },
  retentionRatio: { category: "ratios" },

  revenueGrowth: { category: "growth" },
  netIncomeGrowth: { category: "growth" },
  cagr: { category: "growth" },

  sharePrice: {category: "marketData"},
  marketCapitalization: {category: "marketData"},
  sharesOutstanding: {category: "marketData"},
  weightedAverageSharesOutstanding: {category: "marketData"},
  dilutedSharesOutstanding: {category: "marketData"},

  enterpriseValue: { category: "advanced" },
  evEbitda: { category: "advanced" },
  fcfYield: { category: "advanced text-right" },
  eva: { category: "advanced" },
  workingCapital: { category: "advanced" },
  netWorkingCapital: { category: "advanced" },
};

// Numerical formatting helper
export function safeNum(val: string | number | null | undefined): number {
  if (val === null || val === undefined) return 0;
  const n = parseFloat(String(val).replace(/,/g, ""));
  return isNaN(n) ? 0 : n;
}

export function formatNum(val: string | number | null | undefined): string {
  const n = safeNum(val);
  if (n === 0) return "—";
  return n.toLocaleString("en-MY", { maximumFractionDigits: 0 });
}
